---
- name: 'Install BlueSpice for MediaWiki.'
  user: root
  hosts: mediawiki 
  vars_files:
    - 'vars/vars.yml'

  tasks:

    - name: 'Download BlueSpice-free'
      get_url: url=http://sourceforge.net/projects/BlueSpice/files/latest/download?source=files dest=/tmp/bluespice-free.zip force=no

    - name: 'Install unzip.'
      yum: name=unzip state=latest
 
    - name: 'Unzip BlueSpice-free'
      unarchive: src=/tmp/bluespice-free.zip dest={{ mediawikidir }} copy=no

    - name: 'Check for BlueSpiceDistribution.php.template'
      stat: path='{{ mediawikidir }}'/extensions/BlueSpiceDistribution/BlueSpiceDistribution.php.template
      register: BlueSpiceDistribution

    - name: 'Rename BlueSpiceDistribution.php.template'
      command: mv '{{ mediawikidir }}'//extensions/BlueSpiceDistribution/BlueSpiceDistribution.php.template '{{ mediawikidir }}'//extensions/BlueSpiceDistribution/BlueSpiceDistribution.php
      when: BlueSpiceDistribution.stat.exists

    - name: 'Check for BlueSpiceExtensions.php.template'
      stat: path='{{ mediawikidir }}'/extensions/BlueSpiceExtensions/BlueSpiceExtensions.php.template
      register: BlueSpiceExtensions

    - name: 'Rename BlueSpiceExtensions.php.template'
      command: mv '{{ mediawikidir }}'/extensions/BlueSpiceExtensions/BlueSpiceExtensions.php.template '{{ mediawikidir }}'/extensions/BlueSpiceExtensions/BlueSpiceExtensions.php
      when: BlueSpiceExtensions.stat.exists

    - name: 'Check for data.template'
      stat: path='{{ mediawikidir }}'/extensions/BlueSpiceFoundation/data.template
      register: data

    - name: 'Rename data.template'
      command: mv '{{ mediawikidir }}'/extensions/BlueSpiceFoundation/data.template '{{ mediawikidir }}'/extensions/BlueSpiceFoundation/data
      when: data.stat.exists

    - name: 'Check for data.template'
      stat: path='{{ mediawikidir }}'/extensions/BlueSpiceFoundation/config.template
      register: config

    - name: 'Rename config.template'
      command: mv '{{ mediawikidir }}'/extensions/BlueSpiceFoundation/config.template '{{ mediawikidir }}'/extensions/BlueSpiceFoundation/config
      when: config.stat.exists

    - name: 'Install php-mbstring.'
      yum: name=php-mbstring state=latest

    - name: 'Install php-tidy.'
      yum: name=php-tidy state=latest

    - name: 'Change max_execution_time in php.ini'
      lineinfile: dest=/etc/php.ini regexp='^max_execution_time = 30' line='max_execution_time = 130' state=present

    - name: 'Change post_max_size in php.ini'
      lineinfile: dest=/etc/php.ini regexp='^post_max_size = 8M' line='post_max_size = 32M' state=present

    - name: 'Change upload_max_filesize in php.ini'
      lineinfile: dest=/etc/php.ini regexp='^upload_max_filesize = 2M' line='upload_max_filesize = 32M' state=present

    - name: 'Change upload_tmp_dir in php.ini to /tmp'
      lineinfile: dest=/etc/php.ini regexp='^;upload_tmp_dir =' line='upload_tmp_dir = /tmp' state=present

    - name: 'Restart Apache. Please visit your http://yourmediawiki/installcheck.php to ensure nothing still needs fixing.'
      service: name=httpd state=restarted

